version: 2

updates:
  - package-ecosystem: pip
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    rebase-strategy: auto
    assignees:
      - lialit
    labels:
      - dependencies
      - area: backend
      - priority: P2
    commit-message:
      prefix: deps
      include: scope
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: monthly
      day: monday
      time: "08:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    rebase-strategy: auto
    assignees:
      - lialit
    labels:
      - dependencies
      - area: github
      - priority: P2
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
